version: "3"

tasks:
  postgres:
    desc: "Run postgres14 container with env varables."
    cmds:
      - docker run --name postgres14 -p 5435:5432 -e POSTGRES_USER=root -e POSTGRES_PASSWORD=secret -d postgres:14.7-alpine

  createdb:
    desc: "create database in postgres container"
    cmds: 
      - docker exec -it postgres14 createdb --username=root --owner=root simple_bank

  dropdb:
    desc: "drop database in postgres container"
    cmds: 
      - docker exec -it postgres14 dropdb --username=root --owner=root simple_bank

  migrateup:
    desc: "migrate up cmd"
    cmds:
      - migrate -path db/migration -database "postgresql://root:secret@localhost:5435/simple_bank?sslmode=disable" -verbose up
  
  migratedown:
    desc: "migrate down cmd"
    cmds:
      - migrate -path db/migration -database "postgresql://root:secret@localhost:5435/simple_bank?sslmode=disable" -verbose down
  
  sqlc:
    desc: "sqlc golang "
    cmds: 
      - sqlc generate

  sqlcdocker:
    desc: "run sqlc using dockerfirst run: docker pull kjconroy/sqlc then this cmd"
    cmds: 
      - docker run --rm -v "%cd%:/src" -w /src kjconroy/sqlc generate    

  .PHONY: postgres createdb dropdb migratedb migratedown  